source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, ProfileListView, ChangeProfileView, ChangePasswordView

app_name = "accounts"


urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", RegisterView.as_view(), name='create'),
    path("<int:pk>/", ProfileView.as_view(), name='profile'),
    path("users/", ProfileListView.as_view(), name='list_view'),
    path("change/", ChangeProfileView.as_view(), name='change_profile'),
    path("change/password/", ChangePasswordView.as_view(), name='change_password'),

]

source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts', include("accounts.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.


class Profile(models.Model):
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True, verbose_name="Аватар")
    profile_on_github = models.URLField(verbose_name="Ссылка на GitHub", null=True)
    about = models.TextField(verbose_name="О себе", null=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE,
                                verbose_name="Пользователь", related_name="profile")

    def __str__(self):
        return f"{self.user}"

source/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import widgets
from accounts.models import Profile


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

    def clean(self):
        # if not self.cleaned_data.get("first_name") and not self.cleaned_data.get("last_name"):
        if not (self.cleaned_data.get("first_name") or self.cleaned_data.get("last_name")):
            raise forms.ValidationError(" Необходимо указать 'First name' или 'Last name'!")
        return super().clean()


class UserChangeForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'profile_on_github', 'about']
        widgets = {
            "about": widgets.Textarea(attrs={"placeholder": "введите текст", "cols": 30, "rows": 3})
        }


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, redirect


# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, UpdateView
from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, PasswordChangeForm
from accounts.models import Profile
from webapp.views import DetailView, ListView

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "profile.html"


class ProfileListView(PermissionRequiredMixin, ListView):
    model = Profile
    template_name = "list_user_view.html"
    context_object_name = "users"

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("accounts.view_profile")


class ChangeProfileView(UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = "change_user.html"
    profile_form_class = ProfileChangeForm

    def get_context_data(self, **kwargs):
        context = super(ChangeProfileView, self).get_context_data(**kwargs)
        if "profile_form" not in context:
            context["profile_form"] = self.profile_form_class(instance=self.get_object().profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object= self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        profile_form = self.profile_form_class(instance=self.object.profile,
                                               data=request.POST, files=request.FILES)
        if form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return redirect("accounts:profile", self.object.pk)

    def form_invalid(self, form, profile_form):
        return self.render_to_response(self.get_context_data(form=form,profile_form=profile_form))


class ChangePasswordView(UpdateView):
    model =User
    form_class = PasswordChangeForm
    template_name = "change_password.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.request.user.pk})

    def form_valid(self, form):
        result = super(ChangePasswordView, self).form_valid(form)
        update_session_auth_hash(self.request, self.object)
        return result

source/accounts/templates/change_password.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}

{% block content %}
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-header"><h2>Изменение пароля</h2></div>
  <div class="card-body">
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Изменить"%}
    </form><br/>
  </div>
</div>
{% endblock %}

source/accounts/templates/change_user.html
{% extends "base.html" %}

{% block content %}
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-header"><h2>Редактирование профиля</h2></div>
  <div class="card-body">
    <form action="" method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with fields_only=True %}
        {% include "partial/form.html" with form=profile_form button_text="Редактировать" %}
    </form><br/>
  </div>
</div>
{% endblock %}

source/accounts/templates/list_user_view.html
{% extends "base.html" %}
{% load static %}
{% load request_get_replace_page %}
{% block nav %}

{% endblock %}

{% block content %}
    <h1>Пользователи</h1>
    <div class="row">
        {% for user in users.all %}
            <div class="col-12 col-md-6 col-lg-4 mb-3">
                <div class="card border-info">
                    <div class="card-body">
                        <h5 class="card-title">{{ user.user }}</h5>
                        <a href="{% url 'accounts:profile' user.user.pk %}"
                           class="btn btn-outline-info btn-sm mt-auto d-inline-block w-30">Подробнее</a>
                    </div>
                </div>
            </div>
            {% empty %}
        {% endfor %}
    </div>
{% endblock %}

source/accounts/templates/login.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}

{% block content %}
<div class="top_name card border-info mt-2 ms-4" style="max-width: 20rem;">
  <div class="card-header text-center"><h4>Вход</h4></div>
  <div class="card-body">
    <form method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="text-danger">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <br>
            <input type="password" name="password" id="password">
        </div>
        <br>
        <button class="btn btn-outline-info btn-sm" type="submit">Войти</button>
    </form>
  </div>
</div>
{% endblock %}

source/accounts/templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль{% endblock %}

{% block nav %}
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_profile' %}">Редактировать</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Сменить пароль</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <br>
    <div class="d-flex flex-row bd-highlight mb-3 ">
        <div class="card border-info p-2 bd-highlight" style="width: 18rem;">
            <div class="card-header"><label>Имя пользователя:</label>
                <h3 class="FO">{{ user.username }}</h3>
            </div>
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" class="card-img-top" alt="...">
            {% endif %}
        </div>
        <div class="card border-info p-2 bd-highlight " style="width: 18rem;">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><label>Профиль на GitHub:</label>
                    <h6>{{ user.profile.profile_on_github }}</h6>
                </li>
                <li class="list-group-item"><label>Имя:</label>
                    <h6>{{ user.first_name }}</h6>
                </li>
                <li class="list-group-item"><label>Фамилия:</label>
                    <h6>{{ user.last_name }}</h6>
                </li>
                <li class="list-group-item"><label>Почта:</label>
                    <h6>{{ user.email }}</h6>
                </li>
                <li class="list-group-item"><label>О себе:</label>
                    <h6>{{ user.profile.about }}</h6>
                </li>
            </ul>
        </div>
    </div>
    {% include "partial/projects_list_partial.html" with projects=user.users.all %}
{% endblock %}

source/accounts/templates/user_create.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="top_name card border-info mt-2 ms-4" style="max-width: 20rem;">
    <div class="card-header text-center"><h4>Регистрация</h4></div>
    <div class="card-body">
        <form method="post">
            {% include 'partial/form.html' with button_text="Зарегистрироваться" %}
        </form>
    </div>
</div>
{% endblock %}