source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts', include("accounts.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path

from webapp.views import IndexView, RedirectView, CreateProjectView, \
    TaskView, UpdateTask, DeleteTask, ProjectsView, ProjectDetail,\
    CreateTaskWithProject, UpdateProject, DeleteProject, CreateUserProject, DeleteUserProject

app_name = "webapp"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('tasks/', RedirectView.as_view(pattern_name="index")),
    path('tasks/add/<int:pk>/', CreateTaskWithProject.as_view(), name='create_task'),
    path("task/<int:pk>/", TaskView.as_view(), name="task_view"),
    path('task/<int:pk>/update/', UpdateTask.as_view(), name="update_task"),
    path('task/<int:pk>/delete/', DeleteTask.as_view(), name="delete_task"),


    path('projects/', ProjectsView.as_view(), name="projects_index"),
    path('project/<int:pk>/', ProjectDetail.as_view(), name="project_view"),
    path('project/', CreateProjectView.as_view(), name="project_create"),
    path('projects/<int:pk>/update/', UpdateProject.as_view(), name="update_project"),
    path('projects/<int:pk>/delete/', DeleteProject.as_view(), name="delete_project"),
    path("project/user_add/<int:pk>/", CreateUserProject.as_view(), name="project_user_create"),
    path("project/user_delete/proekt_id/<int:proekt_pk>/user_id/<int:user_pk>/", DeleteUserProject.as_view(), name="delete_user_project"),

]

source/webapp/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.http import urlencode
from django.views.generic import TemplateView, RedirectView, FormView, ListView
from webapp.models import Task
from webapp.forms import TaskForm, SearchForm
from webapp.base_view import FormView as CustomFormView


class IndexView(ListView):
    model = Task
    template_name = "index.html"
    context_object_name = "tasks"
    ordering = "-updated_at"
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        self.sort_value = self.get_sort_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        tasks = Task.objects.all()
        if self.search_value:
            tasks = tasks.filter(Q(author__icontains=self.search_value) | Q(summary__icontains=self.search_value))
        if self.sort_value:
            tasks = tasks.order_by(self.sort_value)
        return tasks

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})
            context["query"] = query
            context["search"] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")

    def get_sort_value(self):
        return self.request.GET.get("sort")


class MyRedirectView(RedirectView):
    url = "https://www.google.ru/"


class TaskView(TemplateView):
    template_name = "task_view.html"

    def get_context_data(self, **kwargs):
        pk = kwargs.get("pk")
        task = get_object_or_404(Task, pk=pk)
        kwargs["task"] = task
        return super().get_context_data(**kwargs)


def index_view_partial(request, create_task_form, status):
    search_form = SearchForm(data=request.GET)
    tasks = Task.objects.all()
    if search_form.is_valid():
        search_value = search_form.cleaned_data.get("search")
        tasks = tasks.filter(summary__contains=search_value)
    tasks = tasks.order_by("-updated_at")
    context = {"tasks": tasks, "search_form": search_form, "create_task_form": create_task_form}
    return render(request, "index.html", context, status=status)


class CreateTask(CustomFormView):
    form_class = TaskForm
    template_name = "create.html"

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_redirect_url(self):
        return redirect("task_view", pk=self.task.pk)


class UpdateTask(FormView):
    form_class = TaskForm
    template_name = "update.html"

    def dispatch(self, request, *args, **kwargs):
        self.task = self.get_objects()
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("task_view", kwargs={"pk": self.task.pk})

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs['instance'] = self.task
        return form_kwargs

    def form_valid(self, form):
        self.task = form.save()
        return super().form_valid(form)

    def get_objects(self):
        return get_object_or_404(Task, pk=self.kwargs.get("pk"))


def delete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == "GET":
        pass
        return render(request, "delete.html", {"task": task})
    else:
        task.delete()
        return redirect("index")

source/webapp/views/base_view.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url


class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class ListView(TemplateView):
    model = None
    context_key = "objects"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.model.objects.all()
        return context

    def get_objects(self):
        return self.model.objects.all()


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ""

    def get_redirect_url(self):
        return redirect(self.redirect_url)

    def get(self, request):
        form = self.form_class()
        context = self.get_context(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_isvalid(form)

    def get_context(self, **kwargs):
        return kwargs

    def form_valid(self, form):
        return self.get_redirect_url()

    def form_isvalid(self, form):
        context = self.get_context(form=form)
        return render(self.request, self.template_name, context)


class UpdateView(View):
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    key_kwarg = 'pk'
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object)
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_context_data(self, **kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(kwargs)
        return context

    def get_redirect_url(self):
        return self.redirect_url


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url

source/webapp/views/projects.py
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Project, Task
from webapp.forms import ProjectForm


class ProjectsView(ListView):
    model = Project
    template_name = "projects/index_list_project.html"
    context_object_name = "projects"
    ordering = "id"
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class ProjectDetail(DetailView):
    template_name = "projects/project_view.html"
    model = Project

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = self.object.tasks.order_by("-created_at")
        return context


class CreateProjectView(PermissionRequiredMixin, CreateView):
    form_class = ProjectForm
    template_name = "projects/create_project.html"

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.add_project")


class UpdateProject(PermissionRequiredMixin, UpdateView):
    form_class = ProjectForm
    template_name = "projects/update_project.html"
    model = Project

    def get_success_url(self):
        return reverse("webapp:project_view", kwargs={"pk": self.object.pk})

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.change_project")


class DeleteProject(PermissionRequiredMixin, DeleteView):
    model = Project
    context_object_name = 'project'
    template_name = "projects/delete_project.html"
    success_url = reverse_lazy('webapp:projects_index')

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.delete_project")


class CreateUserProject(PermissionRequiredMixin, CreateView):

    def get(self, request, *args, **kwargs):
        proekt = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        context = {
            'proekt': proekt,
            'users': User.objects.all()
        }
        return render(request, 'projects/create_user.html', context)

    def post(self, request, *args, **kwargs):
        proekt = get_object_or_404(Project, pk=request.POST.get('project_user'))
        user = int(request.POST.get('user_project'))
        proekt.users.add(user)
        return redirect('webapp:project_view', pk=proekt.pk)

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.add_users_to_the_project")


class DeleteUserProject(PermissionRequiredMixin, View):
    pk_url_kwarg = 'proekt_pk'

    def get(self, request, *args, **kwargs):
        proekt = get_object_or_404(Project, pk=kwargs.get('proekt_pk'))
        user = get_object_or_404(User, pk=kwargs.get('user_pk'))
        context = {
            'proekt': proekt,
            'user': user
        }
        return render(request, 'projects/delete_user.html', context)

    def post(self, request, *args, **kwargs):
        proekt = get_object_or_404(Project, pk=kwargs.get('proekt_pk'))
        user = get_object_or_404(User, pk=kwargs.get('user_pk'))
        proekt.users.remove(user)
        return redirect('webapp:project_view', pk=proekt.pk)

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.remove_users_from_the_project")

source/webapp/views/tasks.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import request
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.http import urlencode
from django.views.generic import RedirectView, ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Task, Project
from webapp.forms import TaskForm, SearchForm, TaskFormProject


class IndexView(ListView):
    model = Task
    template_name = "tasks/index.html"
    context_object_name = "tasks"
    ordering = "-updated_at"
    paginate_by = 9

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        self.sort_value = self.get_sort_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        tasks = Task.objects.all()
        if self.search_value:
            tasks = tasks.filter(Q(author__icontains=self.search_value) | Q(summary__icontains=self.search_value))
        if self.sort_value:
            tasks = tasks.order_by(self.sort_value)
        return tasks

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({'search': self.search_value})
            context["query"] = query
            context["search"] = self.search_value
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get("search")

    def get_sort_value(self):
        return self.request.GET.get("sort")


class MyRedirectView(RedirectView):
    url = "https://www.google.ru/"


class TaskView(DetailView):
    template_name = "tasks/task_view.html"
    model = Task


class CreateTaskWithProject(PermissionRequiredMixin, CreateView):
    form_class = TaskFormProject
    template_name = "tasks/create_tasks_project.html"

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.add_task")

    def detail(request, pk):
        tas = Task.objects.get(id=pk)
        print(tas)
        # posts = tas.users.all()

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get("pk"))
        form.instance.project = project
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:project_view", kwargs={"pk": self.object.project.pk})


class UpdateTask(PermissionRequiredMixin, UpdateView):
    form_class = TaskForm
    template_name = "tasks/update.html"
    model = Task

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.change_task")


class DeleteTask(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy('webapp:index')

    def has_permission(self, **kwargs):
        return self.request.user.has_perm("webapp.delete_task")

source/webapp/templates/projects/create_project.html
{% extends "base.html" %}
{% block title %}Create project{% endblock %}

{% block content %}
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-header"><h2>Создание проекта</h2></div>
  <div class="card-body">
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Создать" %}
    </form><br/>
  </div>
</div>
{% endblock %}

source/webapp/templates/projects/create_user.html
{% extends "base.html" %}
{% block title %}Добавить пользователя{% endblock %}


{% block content %}
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-header"><h2>Добавить пользователя</h2></div>
  <div class="card-body">
    <form action="" method="post">
        {% csrf_token %}
        <select name="user_project">
            {% for user in users %}
                <option value="{{ user.pk }}">{{ user }}</option>
            {% endfor %}
        </select>
        <input type="hidden" name="project_user" value='{{ proekt.pk }}'>
        <button type="submit">Добавить</button>
    </form><br/>
  </div>
</div>
{% endblock %}

source/webapp/templates/projects/delete_project.html
{% extends "base.html" %}
{% block title %}Удаление проекта{% endblock %}

{% block content %}

<div class="top_name card border-info mt-2 ms-4" style="max-width: 20rem;">
  <div class="card-header"><h4>Удаление проекта</h4></div>
  <div class="card-body">
   <form action="" method="post">
{% csrf_token %}
    <h5>Вы уверены что хотите удалить этот проект "{{ project.name }}"?</h5>
    <button class="btn btn-danger" type="submit">Да</button>
    <a class="btn btn-primary" href="{% url 'webapp:project_view' project.pk %}">Нет</a>
</form>
  </div>
</div>
{% endblock %}

source/webapp/templates/projects/delete_user.html
{% extends "base.html" %}
{% block title %}Удаление пользователя{% endblock %}

{% block content %}

<div class="top_name card border-info mt-2 ms-4" style="max-width: 30rem;">
  <div class="card-header"><h4>Удаление пользователя</h4></div>
  <div class="card-body">
   <form action="" method="post">
{% csrf_token %}
    <h5>Вы уверены что хотите удалить этого пользователя "{{ user }}"?</h5>
    <button class="btn btn-danger" type="submit">Да</button>
    <a class="btn btn-primary" href="{% url 'webapp:project_view' proekt.pk %}">Нет</a>
</form>
  </div>
</div>
{% endblock %}

source/webapp/templates/projects/index_list_project.html
{% extends "base.html" %}
{% load static %}
{% load request_get_replace_page %}
{% block nav %}
     {% if request.user.is_authenticated %}
     <li class="nav-item">
         <a class="nav-link" href="{% url 'webapp:project_create' %}">Создать проект</a>
     </li>
     {% endif %}

{% endblock %}

{% block search_form %}
{% endblock %}

{% block content %}

{% include "partial/projects_list_partial.html" %}

{% endblock %}

source/webapp/templates/projects/index_project.html
{% extends "base.html" %}
{% load static %}
{% load request_get_replace_page %}
{% block nav %}
     <li class="nav-item">
         <a class="nav-link" href="{% url 'project_create' %}">Создать проект</a>
     </li>

{% endblock %}

{% block search_form %}
{% endblock %}

{% block content %}
<h1>Проекты</h1>
    <div class="row">
        {% for project in projects %}
            <div class="col-12 col-md-6 col-lg-4 mb-3">
                <div class="card border-info">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.name }}</h5>
                        <a href="{% url 'project_view' project.pk %}" class="btn btn-outline-info btn-sm mt-auto d-inline-block w-30">Подробнее</a>
                    </div>
                </div>
            </div>
        {% empty %}
        {% endfor %}
    </div>

{% endblock %}

source/webapp/templates/projects/project_view.html
{% extends "base.html" %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:projects_index' %}">Проекты</a>
    </li>
    {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:create_task' project.pk %}">Создать задачу</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:update_project' project.pk %}">Редактировать Проект</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" type="button" data-bs-toggle="modal" data-bs-target="#projectDeleteModal">Удалить
                Проект</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webapp:project_user_create' project.pk %}">Добавить пользователя</a>
        </li>
    {% endif %}

    {% block search_form %}
    {% endblock %}

{% endblock %}

{% block content %}
    <br>
    <div class="d-flex bd-highlight mb-3 ">
        <div class="card border-info h-100 text-center" style="width: 20rem;">
            <div class="p-2 bd-highlight"><p class="card-title">Дата создания проекта: {{ project.start_date }}</p>
                {% if project.end_date == None %}
                    <p class="card-title">Дата окончания проекта: Не указана</p>
                {% else %}
                    <p class="card-title">Дата окончания проекта: {{ project.end_date }}</p>
                {% endif %}
            </div>
        </div>
        <div class="ms-auto card border-info h-100 text-center" style="width: 20rem;">
            <div class="p-1 bd-highlight">
                {% for user in project.users.all %}
                    <p>Пользователь: {{ user }} <a href="{% url 'webapp:delete_user_project' project.pk user.pk %}"
                                                   class="btn btn-danger btn-sm">Удалить</a></p>
                    <hr>
                    {% empty %}
                    <p>Пользователя: нет</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row  ms-xl-5">
        <h1 class="card-title  mb-5">проект: {{ project.name }}</h1>
        {% for task in tasks %}
            <div class="col-4 mb-3">
                <div class="card border-info h-100" style="width: 18rem;">
                    <div class="card-body  d-flex flex-column">
                        <h4 class="card-title">{{ task.summary }}</h4>
                        <h6 class="card-subtitle mb-2 text-muted"><b>Статус: </b>
                            {% if not task.status == None %}
                                <p>{{ task.status }}</p>
                            {% else %}
                                <span>Нет</span>
                            {% endif %}
                        </h6>
                        <h6 class="card-subtitle mb-2 text-muted"><b>Типы: </b>
                            {% for type in task.types.all %}
                                <p>{{ type.type_text }}</p>
                                {% empty %}
                                <p>Типов нет</p>
                            {% endfor %}
                        </h6>
                        <a href=" {% url 'webapp:task_view' task.pk %}"
                           class="btn btn-outline-info btn-sm mt-auto d-inline-block w-30">Подробнее</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <h1>Задач нет!</h1>
        {% endfor %}
    </div>
    <div class="modal fade" id="projectDeleteModal" tabindex="-1" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="projectDeleteModal">Удалить Проект</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Вы уверены что хотите удалить запись {{ project.name }}?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Нет</button>
                    <form action="{% url 'webapp:delete_project' project.pk %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-secondary" type="submit">Да</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/projects/update_project.html
{% extends "base.html" %}
{% block title %}Изменение проекта{% endblock %}

{% block content %}
<div class="card border-info mb-3" style="max-width: 18rem;">
  <div class="card-header"><h2>Изменить проект</h2></div>
  <div class="card-body">
    <form action="" method="post">
        {% include "partial/form.html" with button_text="Изменить" %} <a href="{% url 'webapp:project_view' project.pk %}"><input type="button" value="Назад"></a>
    </form>
  </div>
</div>
{% endblock %}